application: cdn-jcayzac
version: 1
runtime: python
api_version: 1

handlers:
- url: /files
  static_dir: files
  expiration: "7d"

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?src/.*
- ^(.*/)?.*\.md
- ^(.*/)?.*\.swp
- ^(.*/)?.*/\.(svn|hg|git)/.*
- ^(.*/)?.*\.po

